server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:usermanagement_db}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:password}
    maxConnections: 10

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changeLog-master.xml
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
security:
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Iddera
resource:
  id: iddera_service
logging:
  level:
    root: INFO
  file:
    name: iddera-user-mgt-service.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
swagger-auth-link: ${SWAGGER_AUTH_LINK:http://127.0.0.1:8080}

user-activation-url: ${USER_ACTIVATION_URL:http://localhost:8080/users/verify-email}
notification-client-url: ${NOTIFICATION_URL:https://iddera-notification-api.herokuapp.com/}
iddera:
  client:
    notification-url: ${NOTIFICATION_URL:https://iddera-notification-api.herokuapp.com/}
    read-time-out: 40
    write-time-out: 40
    connection-time-out: 300


